### ISSUE TITLE
An unhandled exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll

### ISSUE THREAD

**Issue by suemareverton** [step-up-labs/firebase-storage-dotnet#1]
Hello!

Firstly, thank you for your library.

When I run the sample code putting a Console.ReadKey() on last line of the Main method (just after Run().Wait(); call) I get a exception:

An unhandled exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll
System.ObjectDisposedException
Additional information: cannot access closed file

When the exception is thrown the file already was upload correctly.

Same problem occurs when I try to run the code on a Winforms application.

Could you help me figure out why this happens?

Thank you.

**Comment by bezysoftware** [comment]
Should be fixed now, thanks!
