### ISSUE TITLE
Large video does not upload

### ISSUE THREAD

**Issue by cleybsoncardoso** [step-up-labs/firebase-storage-dotnet#10]
I am having problems uploading videos over 50 mb, they are not stored in firebase storage, firebasestorage returns the link empty and no error occurs and the process is 0%

**Comment by LeoVernaza** [comment]
I have the same issue, I'm catching a **TaskCanceledException**  _A task was canceled_ I noticed that the issue is happening after 1.40 minutes... I believe the file size doesn't matter

**Comment by bezysoftware** [comment]
I suppose that's due to the default timeout of HTTP client, I'll push a change where to can change it

**Comment by bezysoftware** [comment]
You can now set custom HTTP client timeout in `FirebaseStorageOptions`
