### ISSUE TITLE
Storage Firebase, bad request 400 for GetDownloadUrlAsync

### ISSUE THREAD

**Issue by medaymenjendoubi** [step-up-labs/firebase-storage-dotnet#14]
I'm trying to get a download URL for a file but I have an exception, i use [FirebaseAuthentication.net](https://www.nuget.org/packages/FirebaseAuthentication.net/) and FirebaseStorage.net in a **VSTO Powerpoint project.**

` var url = await firebaseStorage.Child("parent").Child("filename").GetDownloadUrlAsync();`

**GetDownloadUrlAsync()**  throws an exception
`Exception occured while processing the request.
Url: https://firebasestorage.googleapis.com/v0/b/Your-bucket.appspot.com/o/parent/filename
bad request
Response: {
"error": {
"code": 400,
"message": "Invalid HTTP method/URL pair."
}
}`

> In a **WPF** or **winform** project the function works very well and I can make HTTP calls even with WebClient or RestClient but in a VSTO project always I have the same error Bad request: 400

**Comment by marjandn** [comment]
i have this problem too , does anyone solve this?

**Comment by bezysoftware** [comment]
Can you try using fiddler to sniff the traffic? Perhaps VSTO is changing the request somehow?

**Comment by LDATuan** [comment]
Solution at here:
https://github.com/step-up-labs/firebase-storage-dotnet/issues/2#issuecomment-304611162
