### ISSUE TITLE
How to set mime-type?

### ISSUE THREAD

**Issue by tommed** [step-up-labs/firebase-storage-dotnet#15]
The API clearly shows the ability to set MIME TYPE and other meta-data when uploading a file, which is exposed in the other libraries, but the C# version doesn't seem to support this..? Why you no love C#?

**Comment by bezysoftware** [comment]
You're welcome to do a PR, I currently don't have plans to add support for it

**Comment by tommed** [comment]
Pull request #18 now created. I've also fixed a bug that was introduced recently by another commit. `TimeSpan` should not be compared to `null` as it's a value type (it can't be null). Changed it to check against `default(TimeSpan)`.

**Comment by bezysoftware** [comment]
Deployed in v1.0.2
