### ISSUE TITLE
Firebase Storage Issue

### ISSUE THREAD

**Issue by Supriya-Infinx** [step-up-labs/firebase-storage-dotnet#2]
Hi,

I am using FirebaseStorage.net for uploading image in my c# project
Below is the piece of code i am using for upload purpose
           var task = new FirebaseStorage("path")
                                .Child("data").Child("random").Child("file.png").PutAsync(xmlStream);

However i am getting below listed error

The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I have added reference to required assembly.

Please do the needful.

**Comment by bezysoftware** [comment]
Can you try the sample project? It works for me

**Comment by Supriya-Infinx** [comment]
Above issue is resolved.

Now i am getting below error
{
  "error": {
    "code": 400,
    "message": "Invalid HTTP method/URL pair."
  }
}

**Comment by ghost** [comment]
This could be either authentication issues or simply the format of your bucket name. Verify your authentication and your bucket name.

**Comment by pallavbohara** [comment]
Me too was getting this error-
`{
"error": {
"code": 400,
"message": "Invalid HTTP method/URL pair."
}`
But after simplifying bucket name from "gs://XXXXXX-bdded.appspot.com/" t o "XXXXXXX-bdded.appspot.com" solved my issue

**Comment by eduardopthiago** [comment]
Yes @pallavbohara , it worked for me too. Thank you!

**Comment by arunap** [comment]
Yes @pallavbohara , this worked for me as well. Thanks!!!

**Comment by NathanHanegreefss** [comment]
@pallavbohara  Worked for me! Thank you very much!

**Comment by Malickali** [comment]
@pallavbohara i am new here in firebase can you guide me how to change gs://

**Comment by clouthzine03** [comment]
> Me too was getting this error-
> `{ "error": { "code": 400, "message": "Invalid HTTP method/URL pair." }`
> But after simplifying bucket name from "gs://XXXXXX-bdded.appspot.com/" t o "XXXXXXX-bdded.appspot.com" solved my issue

This solved the problem. Thanks

**Comment by hydro1337x** [comment]
Also worked, thank you !!!

**Comment by mayurgudi** [comment]
> Me too was getting this error-
> `{ "error": { "code": 400, "message": "Invalid HTTP method/URL pair." }`
> But after simplifying bucket name from "gs://XXXXXX-bdded.appspot.com/" t o "XXXXXXX-bdded.appspot.com" solved my issue

Still not working
Code
![image](https://user-images.githubusercontent.com/37340166/84836768-0c666500-b054-11ea-8e03-9d7e6b2ab242.png)

Issue
![image](https://user-images.githubusercontent.com/37340166/84836710-e9d44c00-b053-11ea-9669-c0469bdbf435.png)

**Comment by mayurgudi** [comment]
> Me too was getting this error-
> `{ "error": { "code": 400, "message": "Invalid HTTP method/URL pair." }`
> But after simplifying bucket name from "gs://XXXXXX-bdded.appspot.com/" t o "XXXXXXX-bdded.appspot.com" solved my issue

Thank you so much !! Relieved me

**Comment by Junior-OliveiraDeveloper** [comment]
Thanksssss

**Comment by sinmicsin** [comment]
@pallavbohara hundred thanks man !!! :')

**Comment by mayronjr** [comment]
> Me too was getting this error-
> `{ "error": { "code": 400, "message": "Invalid HTTP method/URL pair." }`
> But after simplifying bucket name from "gs://XXXXXX-bdded.appspot.com/" t o "XXXXXXX-bdded.appspot.com" solved my issue

I'm having the same issue, but my bucket name is already in the format "XXXXXXX-bdded.appspot.com" and it's not working. I'm having this problem in React-Native. In the React aplication it's working normally

**Comment by DANISHPANDITA** [comment]
> Me too was getting this error-
> `{ "error": { "code": 400, "message": "Invalid HTTP method/URL pair." }`
> But after simplifying bucket name from "gs://XXXXXX-bdded.appspot.com/" t o "XXXXXXX-bdded.appspot.com" solved my issue

Can you help me in doing that. I don't know how to do it.

**Comment by Senuka072** [comment]
> Me too was getting this error- `{ "error": { "code": 400, "message": "Invalid HTTP method/URL pair." }` But after simplifying bucket name from "gs://XXXXXX-bdded.appspot.com/" t o "XXXXXXX-bdded.appspot.com" solved my issue

can you explain that i am getting the same issue. please

**Comment by PMLS3** [comment]
how does one change the bucket name? Will all download links still be able to work?

**Comment by L10Messi10** [comment]
This still occurs to me. Never had this before. I also removed those gs:// and still getting this error, I hope someone will help.
