### ISSUE TITLE
how to get all the urls of files in a folder

### ISSUE THREAD

**Issue by kormemis** [step-up-labs/firebase-storage-dotnet#22]
how can I get a list of file url in a folder ? is there a way to get list of all files ?

**Comment by gtaylor44** [comment]
I don't think this is possible. 

You will need to store meta data with a database and fetch from there. You can use cloud functions to hook into file storage CRUD events and make this an atomic operation.

https://stackoverflow.com/questions/37335102/how-to-get-a-list-of-all-files-in-cloud-storage-in-a-firebase-app
