### ISSUE TITLE
Can't upload audio and video files

### ISSUE THREAD

**Issue by Tunga12** [step-up-labs/firebase-storage-dotnet#26]
// Get any Stream — it can be FileStream, MemoryStream or any other type of Stream
            var stream = new MemoryStream(File.ReadAllBytes(textAudio.Text));

            // Construct FirebaseStorage with path to where you want to upload the file and put it there
            var task = new FirebaseStorage("my-bucket.appspot.com")
             .Child("audio")
             .Child(Path.GetFileName(textAudio.Text))
             .PutAsync(stream);

            // Track progress of the upload
            task.Progress.ProgressChanged += (s, ex) => Console.WriteLine($"Progress: {ex.Percentage} %");

            // Await the task to wait until upload is completed and get the download url
            var downloadUrl = await task;

            MessageBox.Show("Download at: " + downloadUrl);

downloadUrl is empty. And when i check the firebase console nothing is uploaded. But the task shows progress until 100%.

**Comment by aleeherasimiuk** [comment]
Hi, any solution?
