### ISSUE TITLE
Firebase - uploading images when internet is offline

### ISSUE THREAD

**Issue by arijitbanerjee73** [step-up-labs/firebase-storage-dotnet#29]
is it also possible to do it with the Firebase storage like send images even if the internet is off, and then when the internet is on again, it will send the images files automatically?

**Comment by bezysoftware** [comment]
It is possible  but not alone with this library, you would need custom implementation. E.g.in my uwp project I save the the upload into a queue and run the upload itself from a background task (triggered once internet becomes available)
