### ISSUE TITLE
Response Data of N/A

### ISSUE THREAD

**Issue by isaac12391** [step-up-labs/firebase-storage-dotnet#42]
Hello, 

I have recently ran into an error using this package. 
it is no longer allowing me to upload files to firebase and returns a response data of "N/A".

please could you advise me, 

kind regards,

Isaac

the error which is logged:
{"The text associated with this error code could not be found.\r\n\r\nA connection with the server could not be established\r\n"}

**Comment by bezysoftware** [comment]
N/A comes from within the library and means the HTTP request failed due to a network issue
