### ISSUE TITLE
how can i generate apikey

### ISSUE THREAD

**Issue by OkancanCosar** [step-up-labs/firebase-storage-dotnet#44]
hi. 
how can i generate apikey for
```c
var auth = new FirebaseAuthProvider(new FirebaseConfig("api_key"));
```

**Comment by BenDelGreco** [comment]
This is not a issue. 
If you need to find the API key go to:

Project Settings -> General -> look for "web API key".

**Comment by OkancanCosar** [comment]
actually i thought that maybe create doc for this. closing
