### ISSUE TITLE
how connect C# and android application to firebase ??

### ISSUE THREAD

**Issue by RiahiRiahi** [step-up-labs/firebase-storage-dotnet#5]
how i can connect my C# application to firebase ?? i connect the android application to firebase but i have problem to do the same with my c#  application :/ ?? i need help :/

**Comment by bezysoftware** [comment]
Read the blog posts:
https://medium.com/step-up-labs/firebase-c-library-5c342989ad18
https://medium.com/step-up-labs/firebase-authentication-c-library-8e5e1c30acc2
https://medium.com/step-up-labs/firebase-storage-c-library-d1656cc8b3c3
