### ISSUE TITLE
FirebaseStorage using Visual Basic 2017

### ISSUE THREAD

**Issue by ghost** [step-up-labs/firebase-storage-dotnet#9]
Hi, Can you please share a sample code how to upload file to Firebase storage using Visual Basic 2017? I have installed FirebaseAuthentication.net and FirebaseStorage.net using NuGet command line. Thanks in Advance!
Tareq

**Comment by bezysoftware** [comment]
Sorry I don't use VB, but if anyone else wants to share their sample, just do a PR
